### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [gyerts/gen-typescript-locale#1]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/gyerts/gen-typescript-locale/blob/master/package.json#L15

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by gyerts** [comment]
But this is a code-generator, not a library. So code generator needs to work with `fs`

**Comment by DanielRuf** [comment]
https://npmjs.org/fs contains no code, `fs` is already part of `node`, `require('fs')` loads the internal NodeJS fs module.

**Comment by gyerts** [comment]
Thank you for the issue. I deleted the use of the library )
